/*
 * File: app/store/Tweets.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Tweets', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Tweet'
    ],

    config: {
        autoLoad: true,
        model: 'MyApp.model.Tweet',
        storeId: 'Tweets',
        proxy: {
            type: 'jsonp',
            url: 'https://api.twitter.com/1/statuses/public_timeline.json?count=20&include_entities=true&include_rts=false&screen_name=richardvelos&count=20',
            reader: {
                type: 'json'
            }
        }
    }
});