/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
    extend: 'Ext.Panel',

    config: {
        ui: 'light',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Twitter Feed',
                items: [
                    {
                        xtype: 'button',
                        hidden: true,
                        itemId: 'Back',
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'panel',
                itemId: 'TweetPreview',
                padding: '12px',
                tpl: [
                    '<div style="float:left; width: 60px;">',
                    '    <img src="{profile_image_url}">',
                    '</div>',
                    '<div style="position: relative; margin-left: 64px;">',
                    '    {name}',
                    '    <br>',
                    '    <div style="color: gray; font-size: 80%;">',
                    '        {description}',
                    '    </div>',
                    '</div>',
                    '',
                    '<div style="clear: both; margin-top: 6px; ',
                    '    background-color: white; padding: 6px; border-radius: 10px;"> ',
                    '    {text}',
                    '    <br>',
                    '    <div style="color: gray; font-size: 80% padding-top: 6px;">',
                    '        Posted: {created_at:date("d M Y h:m")}</div>',
                    '</div>',
                    '    '
                ],
                ui: '',
                scrollable: true
            },
            {
                xtype: 'list',
                itemId: 'TweetList',
                ui: 'round',
                itemTpl: [
                    '<div style="float:left; width: 60px;">',
                    '    <img src="{profile_image_url}">',
                    '</div>',
                    '<div style="margin-left: 62px;">',
                    '    {text}<br>{created_at:date("d M Y")}',
                    '</div>'
                ],
                store: 'Tweets'
            }
        ],
        listeners: [
            {
                fn: 'onBackTap',
                event: 'tap',
                delegate: '#Back'
            },
            {
                fn: 'onTweetListItemTap',
                event: 'itemtap',
                delegate: '#TweetList'
            }
        ]
    },

    onBackTap: function(button, e, options) {
        button.hide();
        this.setActiveItem(0);
        this.down("#TweetList").deselectAll();
    },

    onTweetListItemTap: function(dataview, index, target, record, e, options) {
        this.setActiveItem(1);
        this.down("#Back").show();
        this.down("#TweetPreview").setData(record.data);
    }

});